services :
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://traxuser:traxpassword@mysql:3306/traxdb
  mysql: 
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: traxdb
      MYSQL_USER: traxuser
      MYSQL_PASSWORD: traxpassword
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql  
volumes:
  mysql-data:

  
    
